from .nodes.text_node import NODE_CLASS_MAPPINGS as _m1, NODE_DISPLAY_NAME_MAPPINGS as _d1

NODE_CLASS_MAPPINGS = {**_m1}
NODE_DISPLAY_NAME_MAPPINGS = {**_d1}

WEB_DIRECTORY = "./web"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
